b = [
    ("ALBUM", "Roy"),
    ("ALBUMARTIST", "Amaal Mallik; Ankit Tiwari; Meet Bros Anjjan"),
    ("ARTIST", "K.K."),
    ("COMMENT", "downloaded from lucida.to: https://play.qobuz.com/track/314222289"),
    ("COMPOSER", "Sandeep Nath"),
    (
        "COPYRIGHT",
        "2015 Super Cassettes Industries Private Limited 2015 Super Cassettes Industries Private Limited",
    ),
    ("DATE", "2015-01-08"),
    ("encoder", "Lavf58.76.100"),
    ("GENRE", "Film Soundtracks"),
    ("ISRC", "INS181427685"),
    ("LABEL", "Super Cassettes Industries Private Limited"),
    ("LYRICIST", "Sandeep Nath"),
    ("RATING", "Clean"),
    ("TITLE", "Yaara Re"),
    ("TRACKNUMBER", "5/7"),
]
